# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'telaLogin.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(945, 561)
        MainWindow.setMaximumSize(QtCore.QSize(1000, 700))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setMinimumSize(QtCore.QSize(785, 482))
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frm_fundo = QtWidgets.QFrame(self.centralwidget)
        self.frm_fundo.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.frm_fundo.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frm_fundo.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frm_fundo.setObjectName("frm_fundo")
        self.gridLayout = QtWidgets.QGridLayout(self.frm_fundo)
        self.gridLayout.setContentsMargins(-1, 0, 0, 0)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.frm_fundoLogin = QtWidgets.QFrame(self.frm_fundo)
        self.frm_fundoLogin.setMaximumSize(QtCore.QSize(400, 450))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.frm_fundoLogin.setFont(font)
        self.frm_fundoLogin.setStyleSheet("background-color: rgb(28, 28, 28);\n"
"border-radius: 10px;")
        self.frm_fundoLogin.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frm_fundoLogin.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frm_fundoLogin.setObjectName("frm_fundoLogin")
        self.lblTitulo = QtWidgets.QLabel(self.frm_fundoLogin)
        self.lblTitulo.setGeometry(QtCore.QRect(130, 60, 141, 61))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(20)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.lblTitulo.setFont(font)
        self.lblTitulo.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 20pt \"Arial\";\n"
"background-position:center;")
        self.lblTitulo.setObjectName("lblTitulo")
        self.lblSubtitulo = QtWidgets.QLabel(self.frm_fundoLogin)
        self.lblSubtitulo.setGeometry(QtCore.QRect(90, 115, 221, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.lblSubtitulo.setFont(font)
        self.lblSubtitulo.setStyleSheet("color: rgb(255, 255, 255);")
        self.lblSubtitulo.setObjectName("lblSubtitulo")
        self.lblUsuario = QtWidgets.QLabel(self.frm_fundoLogin)
        self.lblUsuario.setGeometry(QtCore.QRect(24, 160, 71, 16))
        self.lblUsuario.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 12pt \"Arial\";\n"
"")
        self.lblUsuario.setObjectName("lblUsuario")
        self.etyUsuario = QtWidgets.QLineEdit(self.frm_fundoLogin)
        self.etyUsuario.setGeometry(QtCore.QRect(24, 190, 351, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.etyUsuario.setFont(font)
        self.etyUsuario.setStyleSheet("QLineEdit{\n"
"    background-color: #454648;\n"
"    border-radius:5px;\n"
"    border: 2px solid #6C6F71;\n"
"    color:#ffffff;\n"
"}\n"
"\n"
"QLineEdit:focus{\n"
"    border: 2px solid #069E6E;\n"
"}")
        self.etyUsuario.setObjectName("etyUsuario")
        self.lblSenha = QtWidgets.QLabel(self.frm_fundoLogin)
        self.lblSenha.setGeometry(QtCore.QRect(24, 243, 71, 16))
        self.lblSenha.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 12pt \"Arial\";\n"
"")
        self.lblSenha.setObjectName("lblSenha")
        self.etySenha = QtWidgets.QLineEdit(self.frm_fundoLogin)
        self.etySenha.setGeometry(QtCore.QRect(24, 273, 351, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.etySenha.setFont(font)
        self.etySenha.setStyleSheet("QLineEdit{\n"
"    background-color: #454648;\n"
"    border-radius:5px;\n"
"    border: 2px solid #6C6F71;\n"
"    color:#ffffff;\n"
"}\n"
"\n"
"QLineEdit:focus{\n"
"    border: 2px solid #069E6E;\n"
"}")
        self.etySenha.setEchoMode(QtWidgets.QLineEdit.Password)
        self.etySenha.setObjectName("etySenha")
        self.btnLogin = QtWidgets.QPushButton(self.frm_fundoLogin)
        self.btnLogin.setGeometry(QtCore.QRect(24, 350, 351, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.btnLogin.setFont(font)
        self.btnLogin.setStyleSheet("QPushButton{\n"
"    background-color:#069E6E;\n"
"    color:#ffffff;\n"
"    border-radius:5px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color:#047b55;\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    background-color: rgb(2, 45, 29);\n"
"}")
        self.btnLogin.setObjectName("btnLogin")
        self.chkboxExibirSenha = QtWidgets.QCheckBox(self.frm_fundoLogin)
        self.chkboxExibirSenha.setGeometry(QtCore.QRect(24, 320, 101, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.chkboxExibirSenha.setFont(font)
        self.chkboxExibirSenha.setStyleSheet("QCheckBox{\n"
"    color: #6C6F71;\n"
"}\n"
"\n"
"QCheckBox::indicator{\n"
"    border: 3px solid #6C6F71;\n"
"    width: 12px;\n"
"    height:12px;\n"
"    border-radius:5px;\n"
"}\n"
"\n"
"QCheckBox::indicator:checked{\n"
"    border: 3px solid #069E6E;\n"
"    background-color: #069E6E;\n"
"}\n"
"\n"
"")
        self.chkboxExibirSenha.setObjectName("chkboxExibirSenha")
        self.gridLayout.addWidget(self.frm_fundoLogin, 1, 1, 1, 1)
        self.frm_imgLogo = QtWidgets.QFrame(self.frm_fundo)
        self.frm_imgLogo.setMaximumSize(QtCore.QSize(295, 16777215))
        self.frm_imgLogo.setStyleSheet("background-image: url(:/imagens/imgLogo.png);\n"
"background-repeat:no-repeat;\n"
"background-position:left;")
        self.frm_imgLogo.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frm_imgLogo.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frm_imgLogo.setObjectName("frm_imgLogo")
        self.gridLayout.addWidget(self.frm_imgLogo, 1, 0, 1, 1)
        self.verticalLayout.addWidget(self.frm_fundo)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 945, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Login | Sistema de Reconhecimento Facial"))
        self.lblTitulo.setText(_translate("MainWindow", "Fazer login "))
        self.lblSubtitulo.setText(_translate("MainWindow", "Faça o login para acessar o sistema."))
        self.lblUsuario.setText(_translate("MainWindow", "Usuário:"))
        self.etyUsuario.setPlaceholderText(_translate("MainWindow", "Insira o seu usuário"))
        self.lblSenha.setText(_translate("MainWindow", "Senha:"))
        self.etySenha.setPlaceholderText(_translate("MainWindow", "Insira a sua senha"))
        self.btnLogin.setText(_translate("MainWindow", "Login"))
        self.chkboxExibirSenha.setText(_translate("MainWindow", "Exibir senha"))
import imagens.imagens_usadas_rc
